import './globals.css'
import MainHeader from '@/components/main-header/main-header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <MainHeader/>
        {children}
      </body>
    </html>
  )
}
